name: Terraform Destroy

on:
  push:
    tags:
      - 'destroy-*'  # Trigger on tags with the 'destroy-' prefix

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Determine Environment
        id: environment
        run: |
          # Extract the environment name from the tag
          environment=$(echo "${GITHUB_REF#refs/tags/destroy-}")
          echo "::set-output name=environment::${environment}"
        shell: bash

      - name: Destroy Terraform Resources
        run: |
          cd "terraform/${{ steps.environment.outputs.environment }}"
          terraform init
          terraform destroy -auto-approve
        env:
          TF_VAR_environment: ${{ steps.environment.outputs.environment }}
